run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - varnamelen
    #- gofumpt
    - gci

issues:
  exclude-use-default: false
  max-same-issues: 5
  max-issues-per-linter: 0
  max-issues: 50

linters-settings:
  errcheck:
    check-blank: true
  gci:
    sections: ["standard", "default", "prefix(github.com/Bl00mGuy)"]
  gofumpt:
    extra-rules: true
  varnamelen:
    min-length: 3
  wsl:
    allow-assign-and-call: false
    allow-cuddle-declarations: false
    allow-trailing-comment: false
