run:
  timeout: 5m
  tests: true
  concurrency: 4

linters:
  enable-all: true
  disable:
    - lll
    - gocyclo

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment
  gocritic:
    settings:
      captLocal:
        paramsOnly: false
  funlen:
    lines: 100
    statements: 50
    ignore-comments: true
  depguard:
    rules:
      legacy:
        deny:
          - pkg: "github.com/golang/protobuf"
            desc: "Используйте google.golang.org/protobuf вместо этого."
          - pkg: "github.com/satori/go.uuid"
            desc: "Используйте github.com/google/uuid; пакет satori не поддерживается."

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

output:
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
  sort-order:
    - severity
    - file
